---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-7
    ports:
        - '27017:27017'  # open up port for external access

suites:
  - name: default
    run_list:
      - recipe[1_MongoDB::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
